### ISSUE TITLE
MariaDB 10.4 server removed on upgrade from CentOS 7 to 8

### ISSUE THREAD

**Issue by bathomas** [AlmaLinux/leapp-repository#103]
**Actual behavior**
MariaDB server 10.4 was installed on CentOS 7, when upgrading to 8, rpms were removed but not replaced. This results in a non-functional PHP app.

**To Reproduce**

1. Install LAMP stack on CentOS 7 using Maria 10.4 from [MariaDB repo](http://yum.mariadb.org/10.4/centos7-amd64).
2. Upgrade to Alma 8.
3. App is non-functional as there is no MariaDB server installed.

**Expected behavior**
- MariaDB is upgraded to 11.3
- User is warned that MariaDB will undergo a major version upgrade if continuing with OS upgrade.

**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
- CentOS 7.9

```
# rpm -qa "*leapp*"
leapp-deps-el8-5.0.8-100.202203181036Z.249925a3.master.el8.noarch
leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.19.noarch
leapp-data-almalinux-0.2-5.el7.noarch
python2-leapp-0.14.0-1.el7.noarch
leapp-repository-deps-el8-5.0.8-100.202203181036Z.249925a3.master.el8.noarch
leapp-0.14.0-1.el7.noarch
```

[leapp-logs-mariadb.tar.gz](https://github.com/AlmaLinux/leapp-repository/files/14626767/leapp-logs-mariadb.tar.gz)

**Additional context**
- It should be possible to upgrade MariaDB prior to upgrade.

**Comment by andrewlukoshko** [comment]
Fixed
