### ISSUE TITLE
disk space issue: Not enough space available for creating required disk images in /var/lib/leapp/scratch

### ISSUE THREAD

**Issue by atoomic** [AlmaLinux/leapp-repository#29]
When updating a customer server using cPanel&WHM from CentOS 7 to AlmaLinux 8 we can see a failure from `/var/lib/leapp/scratch` claiming that it needs a lot of disk space

`Needs 155648 MiB` this seems to be a lot of disk space for the elevate process `~156G`
(note that using a more human friendly unit when going above 1G would be nice)

We do not know from that error what partition needs such amount of disk space. I'm not sure neither why that amount is required.

cPanel requirements listed here https://cpanel.github.io/elevate/blockers/ are not aware of such limitations 
```
/boot: 120 MB
/usr/local/cpanel: 1.5 GB
/var/lib: 3 GB
```

Could you provide or point the known list of disk space limitations? I guess some are dynamic?

Error from `leapp`
```
2022-12-03 01:41:19.140 ERROR    PID: 17560 leapp.workflow.TargetTransactionFactsCollection.target_userspace_creator: Not enough space available for creating required disk images in /var/lib/leapp/scratch. Needed: 155648 MiB
```

The system has the following disk space available 
```
[16:03:42 cp root@94508712 ~]cPs# df -h
Filesystem                                        Size  Used Avail Use% Mounted on
devtmpfs                                          2.9G     0  2.9G   0% /dev
tmpfs                                             2.9G     0  2.9G   0% /dev/shm
tmpfs                                             2.9G   26M  2.9G   1% /run
tmpfs                                             2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/mapper/centos_static--98--115--153--46-root   50G   27G   23G  55% /
/dev/sda1                                         497M  283M  214M  57% /boot
/dev/mapper/centos_static--98--115--153--46-home   25G  491M   24G   2% /home
/dev/sdb1                                         335G  7.9G  310G   3% /home/users
tmpfs                                             581M     0  581M   0% /run/user/0
/dev/sdc  
```

thanks for your help

**Comment by prilr** [comment]
@atoomic Space requirements for the upgrade tend to vary substantially, depending on what packages were installed on the system, what repositories were enabled, what was available from them, etc.

However, space requirements like these are not normal.
Do you have the logs (files from `var/log/leapp`) from this machine available?
Without them, it's going to be hard to tell what went wrong, since there's no data on the list of packages Leapp is attempting to download.

**Comment by atoomic** [comment]
Thanks for your reply. Here are the logs from the customer server where that disk space was requested.
Hope it helps.
thanks 

[leapp-report.txt](https://github.com/AlmaLinux/leapp-repository/files/10179417/leapp-report.txt)
[leapp-upgrade.log](https://github.com/AlmaLinux/leapp-repository/files/10179418/leapp-upgrade.log)

**Comment by prilr** [comment]
It does help. Could you also get `/var/log/leapp/dnf-plugin-data.txt` from the same machine, by any chance?

**Comment by toddr** [comment]
Is there any private information in these files we should be clearing?

**Comment by prilr** [comment]
Not to my knowledge. 
`dnf-plugin-data.txt`, for instance, just contains the DNF configuration leapp constructs during the initial upgrade phase, to then feed it to DNF inside the isolated target OS environment.

**Comment by prilr** [comment]
@atoomic Do I understand it correctly that this machine has 76 XFS mountpoints with ftype = 0?
As far as I can tell, Leapp calculates the needed space required based in part on that number.

**Comment by atoomic** [comment]
Unfortunately we do not have access anymore to the server.
I was trying to understand the `156G` disk space requirement.
The number of mount points could explain part of it.
thanks
