### ISSUE TITLE
Rebase leapp-repository to 0.19.0 upstream version

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/leapp-repository#86]
Currently ELevate uses leapp-repository 0.16.0 which is outdated.
We need to rebase on top of recently released 0.19.0 version.
**almalinux-ng** branch should be used.
It's also necessary to drop all CloudLinux and cPanel related code because CloudLinux now uses own fork of leapp-repository https://github.com/cloudlinux/leapp-repository

**Comment by andrewlukoshko** [comment]
The following commits should be applied on top of `almalinux-ng` branch:
https://github.com/AlmaLinux/leapp-repository/commit/0f31a666e94e22c51e6a949dd7450bff92cdc9ea
https://github.com/AlmaLinux/leapp-repository/commit/3b0e3da0ba4f9ab77c6992ab0ae80e49093d593e
https://github.com/AlmaLinux/leapp-repository/commit/6c7c4b9d55a51e4fad208c883c512ac87eeb288b
https://github.com/AlmaLinux/leapp-repository/commit/041e84db618561218eee09f0101fa935d3da6321
https://github.com/AlmaLinux/leapp-repository/commit/04c78a211f5fc2a86dd4aaa627d4a442b9a83485
https://github.com/AlmaLinux/leapp-repository/commit/66fe44ed2c92ee3a0ae0cabe50df9fb5bdbb8d1f
https://github.com/AlmaLinux/leapp-repository/commit/3ac3cb65c2668990971cbf528c0d6b6a77e5e1cb
https://github.com/AlmaLinux/leapp-repository/commit/b92b7167971c4702543314ba748da079c51bb78e
https://github.com/AlmaLinux/leapp-repository/commit/449b5f12d9681a42f4a4178e7e418f7709a19c97
https://github.com/AlmaLinux/leapp-repository/commit/e4ce70da849f09c811ba59bcf857614200d4eaa7
https://github.com/AlmaLinux/leapp-repository/commit/aebbf63e816f05f42c62a2fcc2606b37130016c6
https://github.com/AlmaLinux/leapp-repository/commit/d7e5f72908432a5c073b79252b900cebc307c313
https://github.com/AlmaLinux/leapp-repository/commit/16a1f5e89d43fb01c9cd5f610ad5121d0472fb48
https://github.com/AlmaLinux/leapp-repository/commit/c847c4a3fdbae7536481720d19384550e5993961
https://github.com/AlmaLinux/leapp-repository/commit/65ca7fa85744cf2d203ba7cfe5a4da8b4659674b
https://github.com/AlmaLinux/leapp-repository/commit/de6e99b1840775301f6b49a13e3e197c0010b504
https://github.com/AlmaLinux/leapp-repository/commit/67956b80df2d90a092ccb1d5a9f4a6e949dc93d8
https://github.com/AlmaLinux/leapp-repository/commit/d1ae79368692366c47d717566695942a95895d01

This is phase 1, without 3rd party vendors yet.

**Comment by yuravk** [comment]
The phase 1 done on https://github.com/yuravk/leapp-repository/tree/almalinux-ng

**Comment by toddr** [comment]
Could you please clarify what "cpanel" changes you're dropping? We weren't aware you had any.

**Comment by andrewlukoshko** [comment]
@toddr you can check some panels related PRs here:
https://github.com/AlmaLinux/leapp-repository/pulls?q=panel

**Comment by toddr** [comment]
cPanel is using the cPanel related commits. We added these to support additional repos. Per previous discussions, this was going to be how we added other repos so they would properly upgrade the rpms that they came with. Is your plan to leave these commits out?

**Comment by andrewlukoshko** [comment]
We'll continue to maintain additional repos support with configuration in [vendors.d](https://github.com/AlmaLinux/leapp-data/tree/main/vendors.d).
So basically this AlmaLinux variant of leapp-repository will switch to follow [upstream](https://github.com/oamg/leapp-repository) with only 2 differences:
- AlmaLinux/CentOS/Oracle/Rocky/EuroLinux/etc distributions support
- Additional repos support

They are enough to reach ELevate project goals to allow migrations between major versions of different RHEL-based operating systems with extra repos like EPEL with minimal overhead and receiving latest updates from upstream (important for 8 to 9 migrations). 

CloudLinux maintains [own leapp-repository fork](https://github.com/cloudlinux/leapp-repository) that contains all current commits + many new CloudLinux OS and panels related ones but as I said it's a fork so updating to new upstream versions will be often delayed. Not a problem for 7 to 8 migtations but 8 to 9 migrations may require more frequent updates from upstream.

So you can choose which leapp-repository repo works better for your needs.
